version: "2"

run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - bidichk
    - canonicalheader
    - testifylint
    - wsl
    #- depguard
    #- dogsled
    - dupl
    - errcheck
    #- funlen
    #- gochecknoinits
    - goconst
    - gocritic
    #- gocyclo
    #- gofmt
    #- goimports
    #- gomnd
    #- goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - staticcheck
    - unconvert
    - unused

linters-settings:
  stylecheck:
    checks: ["-ST1003"]
