// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Repo",
            "url": "https://github.com/GeekchanskiY/E2E"
        },
        "license": {
            "name": "MIT License",
            "url": "https://github.com/GeekchanskiY/E2E/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/users/register": {
            "post": {
                "description": "Registers user and creates permission group for him.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Register user",
                "parameters": [
                    {
                        "description": "user id",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/finworker_internal_models_requests_users.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "user registered",
                        "schema": {
                            "$ref": "#/definitions/finworker_internal_models_responses_users.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "test",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{userId}": {
            "get": {
                "description": "get user by user id",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "user id",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "finworker_internal_models_requests_users.RegisterRequest": {
            "type": "object",
            "properties": {
                "birthday": {
                    "description": "Birthday. Age must be \u003e 18.",
                    "type": "string"
                },
                "gender": {
                    "description": "Gender. ` + "`" + `male` + "`" + `/` + "`" + `female` + "`" + `.",
                    "type": "string"
                },
                "name": {
                    "description": "Name. just to be displayed",
                    "type": "string"
                },
                "password": {
                    "description": "Password, which will be used with secret",
                    "type": "string"
                },
                "preferred_bank_name": {
                    "description": "PreferredBankName is used to created initial salary wallet",
                    "type": "string"
                },
                "salary": {
                    "description": "Salary may be 0, then you'll need to manually set your salary every month",
                    "type": "integer"
                },
                "salary_currency": {
                    "description": "SalaryCurrency",
                    "type": "string"
                },
                "salary_date": {
                    "description": "SalaryDate may be zero, then you'll need to confirm achieving your salary",
                    "type": "string"
                },
                "username": {
                    "description": "Username, which will be displayed and unique.",
                    "type": "string"
                }
            }
        },
        "finworker_internal_models_responses_users.RegisterResponse": {
            "type": "object",
            "properties": {
                "permission_group": {
                    "description": "PermissionGroup that contains user as owner",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.PermissionGroup"
                        }
                    ]
                },
                "user": {
                    "description": "User new user data",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.User"
                        }
                    ]
                },
                "user_permission": {
                    "description": "UserPermission confirms that user is owner of the permission group",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.UserPermission"
                        }
                    ]
                },
                "wallet": {
                    "description": "Wallet created initial wallet for salary",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Wallet"
                        }
                    ]
                }
            }
        },
        "models.AccessLevel": {
            "type": "string",
            "enum": [
                "owner",
                "full",
                "read"
            ],
            "x-enum-varnames": [
                "AccessLevelOwner",
                "AccessLevelFull",
                "AccessLevelRead"
            ]
        },
        "models.Currency": {
            "type": "string",
            "enum": [
                "USD",
                "EUR",
                "BYN",
                "RUB"
            ],
            "x-enum-varnames": [
                "CurrencyUSD",
                "CurrencyEUR",
                "CurrencyBYN",
                "CurrencyRUB"
            ]
        },
        "models.PermissionGroup": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "birthday": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.UserPermission": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "level": {
                    "$ref": "#/definitions/models.AccessLevel"
                },
                "permission_group_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.Wallet": {
            "type": "object",
            "properties": {
                "bank_id": {
                    "description": "BankID refers to internal bank id",
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "currency": {
                    "$ref": "#/definitions/models.Currency"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isSalary": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "permissionGroupId": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "E2E",
	Description:      "Описание взаимодействия и работы внутренних моделей E2E CRM",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
