basePath: /
consumes:
- application/json
definitions:
  finworker_internal_models_requests_users.RegisterRequest:
    properties:
      birthday:
        description: Birthday. Age must be > 18.
        type: string
      gender:
        description: Gender. `male`, `female` or `battle helicopter`.
        type: string
      name:
        description: Name. just to be displayed
        type: string
      password:
        description: Password, which will be used with secret
        type: string
      username:
        description: Username, which will be displayed and unique.
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: Repo
    url: https://github.com/GeekchanskiY/E2E
  description: Описание взаимодействия и работы внутренних моделей E2E CRM
  license:
    name: MIT License
    url: https://github.com/GeekchanskiY/E2E/blob/main/LICENSE
  title: E2E
  version: "0.0"
paths:
  /users/{userId}:
    get:
      consumes:
      - application/json
      description: get user by user id
      parameters:
      - description: user id
        in: path
        name: userId
        required: true
        type: integer
      responses:
        "200":
          description: OK
      summary: Get user
      tags:
      - users
  /users/register:
    post:
      consumes:
      - application/json
      description: register user
      parameters:
      - description: user id
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/finworker_internal_models_requests_users.RegisterRequest'
      responses:
        "200":
          description: OK
      summary: Register user
      tags:
      - users
produces:
- application/json
schemes:
- http
swagger: "2.0"
