basePath: /
consumes:
- application/json
definitions:
  finworker_internal_models_requests_users.RegisterRequest:
    properties:
      birthday:
        description: Birthday. Age must be > 18.
        type: string
      gender:
        description: Gender. `male`/`female`.
        type: string
      name:
        description: Name. just to be displayed
        type: string
      password:
        description: Password, which will be used with secret
        type: string
      preferred_bank_name:
        description: PreferredBankName is used to created initial salary wallet
        type: string
      salary:
        description: Salary may be 0, then you'll need to manually set your salary
          every month
        type: integer
      salary_currency:
        description: SalaryCurrency
        type: string
      salary_date:
        description: SalaryDate may be zero, then you'll need to confirm achieving
          your salary
        type: string
      username:
        description: Username, which will be displayed and unique.
        type: string
    type: object
  finworker_internal_models_responses_users.RegisterResponse:
    properties:
      permission_group:
        allOf:
        - $ref: '#/definitions/models.PermissionGroup'
        description: PermissionGroup that contains user as owner
      user:
        allOf:
        - $ref: '#/definitions/models.User'
        description: User new user data
      user_permission:
        allOf:
        - $ref: '#/definitions/models.UserPermission'
        description: UserPermission confirms that user is owner of the permission
          group
      wallet:
        allOf:
        - $ref: '#/definitions/models.Wallet'
        description: Wallet created initial wallet for salary
    type: object
  models.AccessLevel:
    enum:
    - owner
    - full
    - read
    type: string
    x-enum-varnames:
    - AccessLevelOwner
    - AccessLevelFull
    - AccessLevelRead
  models.Currency:
    enum:
    - USD
    - EUR
    - BYN
    - RUB
    type: string
    x-enum-varnames:
    - CurrencyUSD
    - CurrencyEUR
    - CurrencyBYN
    - CurrencyRUB
  models.PermissionGroup:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
    type: object
  models.User:
    properties:
      birthday:
        type: string
      gender:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  models.UserPermission:
    properties:
      created_at:
        type: string
      id:
        type: integer
      level:
        $ref: '#/definitions/models.AccessLevel'
      permission_group_id:
        type: integer
      user_id:
        type: integer
    type: object
  models.Wallet:
    properties:
      bank_id:
        description: BankId refers to internal bank id
        type: integer
      createdAt:
        type: string
      currency:
        $ref: '#/definitions/models.Currency'
      description:
        type: string
      id:
        type: integer
      isSalary:
        type: boolean
      name:
        type: string
      permissionGroupId:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    name: Repo
    url: https://github.com/GeekchanskiY/E2E
  description: Описание взаимодействия и работы внутренних моделей E2E CRM
  license:
    name: MIT License
    url: https://github.com/GeekchanskiY/E2E/blob/main/LICENSE
  title: E2E
  version: "0.0"
paths:
  /users/{userId}:
    get:
      consumes:
      - application/json
      description: get user by user id
      parameters:
      - description: user id
        in: path
        name: userId
        required: true
        type: integer
      responses:
        "200":
          description: OK
      summary: Get user
      tags:
      - users
  /users/register:
    post:
      consumes:
      - application/json
      description: Registers user and creates permission group for him.
      parameters:
      - description: user id
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/finworker_internal_models_requests_users.RegisterRequest'
      responses:
        "201":
          description: user registered
          schema:
            $ref: '#/definitions/finworker_internal_models_responses_users.RegisterResponse'
        "400":
          description: test
          schema:
            type: string
      summary: Register user
      tags:
      - users
produces:
- application/json
schemes:
- http
swagger: "2.0"
